inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*' # Inheriting BaseService without calling super is OK.

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "scripts/*"
    - "spec/**/*"
    - "config/initializers/*"
    - "config/environments/*"
    - "config/routes.rb"

Layout/LineLength:
  Max: 120
